# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build for Windows

on:
  push:
    tags:
      - 'v*' # Auto-trigger only for new tags
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}\build" >> "$GITHUB_OUTPUT"

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.3'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=cl
          -DCMAKE_C_COMPILER=cl
          -DCMAKE_BUILD_TYPE=Release
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

      - name: Get Qt Dependency Libs
        run: windeployqt --release --no-translations ${{ steps.strings.outputs.build-output-dir }}\Release\qlogexplorer.exe

      - name: Build Installed
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
        with:
          path: packaging/win/innosetup.iss
          options: |
            /O+
            /DSrcDir=${{ github.workspace }}
            /DBuildBinDir=${{ steps.strings.outputs.build-output-dir }}\Release

      - name: Upload installer as artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: QLogExplorer-Installer
          path: ${{ steps.strings.outputs.build-output-dir }}\Release\QLogExplorer-Win64-Setup.exe

      - name: Publish GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.strings.outputs.build-output-dir }}\Release\QLogExplorer-Win64-Setup.exe
